services:
  sniffer:
    build:
      context: .
    # image: fillol/chronicle-sniffer:latest # Or your preferred pre-built image
    container_name: chronicle-sniffer-instance
    restart: unless-stopped
    env_file:
      - .env
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./gcp-key:/app/gcp-key:ro
      - ./captures:/app/captures