# docker-compose.yaml per avviare il container dello sniffer on-premises

services:
  sniffer:
    build: .
    container_name: chronicle-sniffer
    restart: unless-stopped
    env_file:
      - .env
    network_mode: "host"
    cap_add:
      - NET_ADMIN # Permessi per gestire interfacce di rete
      - NET_RAW   # Permessi per leggere pacchetti raw

    volumes:
      - ./sniffer/gcp-key:/app/gcp-key:ro # Monta la chiave in sola lettura