services:
  sniffer:
    image: fillol/chronicle-sniffer:latest
    build:
      context: .
    container_name: chronicle-sniffer
    restart: unless-stopped
    env_file:
      - .env
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./gcp-key:/app/gcp-key:ro
      - ./captures:/app/captures